#!/usr/bin/env python3
"""Generate a Word (.docx) migration mapping document.

Creates `MIGRATION_MAPPING.docx` in the same folder.
"""
from docx import Document
from docx.shared import Inches
import os

OUT_NAME = "MIGRATION_MAPPING.docx"

ROWS = [
    ("id", "uuid PRIMARY KEY", "(generated)", "Postgres `id` is generated by gen_random_uuid() on insert; script does not provide it."),
    ("external_id", "int8 NOT NULL", "APID", "Mapped from APID. Must be present; consider filtering or fallback if NULL."),
    ("new_id", "uuid", "(none)", "Left NULL. Self-referencing FK not set during import."),
    ("release_version", "text NOT NULL", "(none)", "Set to literal 'migrated' for all imported rows."),
    ("invalid", "boolean NOT NULL", "(none)", "Set to false for all imported rows."),
    ("virtual_medicinal_product_id", "int8 NOT NULL", "VPID", "Mapped from VPID (bigint). If NULL may violate NOT NULL constraint."),
    ("name", "text NOT NULL", "NM", "Mapped from NM (varchar)."),
    ("supplier_code", "int8", "(none)", "Not available in source — intentionally left NULL."),
    ("lic_auth_code", "int2", "DESC", "Parsed from DESC when numeric; clamped to smallint range; else NULL."),
    ("created_at", "timestamptz NOT NULL", "created_at", "Mapped from created_at; if NULL may violate NOT NULL constraint."),
]


def make_doc(out_path: str):
    doc = Document()
    doc.add_heading('Migration mapping: MySQL amp -> Postgres public.dmd_actual_medicinal_products', level=1)
    doc.add_paragraph('This document lists each target column, the Postgres type, the source column in MySQL, and any transformations or notes.')

    table = doc.add_table(rows=1, cols=4)
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Target column'
    hdr_cells[1].text = 'Postgres type'
    hdr_cells[2].text = 'Source (MySQL amp)'
    hdr_cells[3].text = 'Transformation / Notes'

    for target, ptype, source, notes in ROWS:
        row_cells = table.add_row().cells
        row_cells[0].text = target
        row_cells[1].text = ptype
        row_cells[2].text = source
        row_cells[3].text = notes

    doc.add_heading('Additional notes', level=2)
    doc.add_paragraph(' - The script checks existing external_id values in Postgres to avoid inserting duplicates.')
    doc.add_paragraph(' - If MySQL data contains NULL APID values, update the script to skip those rows or derive a fallback.')
    doc.add_paragraph(' - updated_at is currently ignored by the script.')
    doc.add_paragraph(' - new_id (self FK) is not computed; post-process if necessary.')

    doc.add_heading('Example transformed JSON for one row', level=2)
    doc.add_paragraph('''{
  "external_id": 12345,
  "release_version": "migrated",
  "invalid": false,
  "virtual_medicinal_product_id": 67890,
  "name": "Example Product",
  "supplier_code": null,
  "lic_auth_code": 12,
  "created_at": "2024-01-01T12:00:00Z"
}''')

    doc.add_heading('Recommended actions before running import', level=2)
    doc.add_paragraph(' - Verify APID completeness (no NULLs) or modify the script to skip/fallback.')
    doc.add_paragraph(' - Backup the target Postgres table or run in staging first.')
    doc.add_paragraph(' - Run with --dry-run to review counts and sample transformed rows.')

    doc.save(out_path)


if __name__ == '__main__':
    here = os.path.dirname(__file__)
    out = os.path.join(here, OUT_NAME)
    make_doc(out)
    print(f'Wrote {out}')
