-- qitech.users definition

CREATE TABLE `users` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `job_id` bigint unsigned DEFAULT NULL,
  `position_id` int unsigned DEFAULT NULL,
  `is_registered` tinyint(1) DEFAULT NULL,
  `registration_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location_regulatory_body_id` int unsigned DEFAULT NULL,
  `country_of_practice` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `first_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `surname` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `mobile_no` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_updated_at` timestamp NULL DEFAULT NULL,
  `email_verification_key` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `remember_token` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `is_archived` tinyint(1) NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `is_suspended` tinyint(1) NOT NULL DEFAULT '0',
  `selected_head_office_id` int unsigned DEFAULT NULL,
  `last_login_at` timestamp NULL DEFAULT NULL,
  `last_login_location_id` int unsigned DEFAULT NULL,
  `is_email_hidden` tinyint NOT NULL DEFAULT '0',
  `is_phone_hidden` tinyint NOT NULL DEFAULT '0',
  `block_comment` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `middlename` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `registration_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_form_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  KEY `users_position_id_index` (`position_id`),
  KEY `users_location_regulatory_body_id_index` (`location_regulatory_body_id`),
  KEY `users_selected_head_office_id_index` (`selected_head_office_id`),
  KEY `users_last_login_location_id_index` (`last_login_location_id`),
  KEY `users_job_id_foreign` (`job_id`),
  KEY `users_last_form_id_foreign` (`last_form_id`),
  CONSTRAINT `users_job_id_foreign` FOREIGN KEY (`job_id`) REFERENCES `user_jobs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `users_last_form_id_foreign` FOREIGN KEY (`last_form_id`) REFERENCES `be_spoke_form` (`id`),
  CONSTRAINT `users_last_login_location_id_foreign` FOREIGN KEY (`last_login_location_id`) REFERENCES `locations` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `users_location_regulatory_body_id_foreign` FOREIGN KEY (`location_regulatory_body_id`) REFERENCES `location_regulatory_bodies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `users_position_id_foreign` FOREIGN KEY (`position_id`) REFERENCES `positions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `users_selected_head_office_id_foreign` FOREIGN KEY (`selected_head_office_id`) REFERENCES `head_offices` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5117 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;